from langchain_community.document_loaders.pdf import PyPDFDirectoryLoader,PyPDFLoader
# from langchain_community.document_loaders import Textloader
from langchain_community.vectorstores import Chroma

from langchain_text_splitters import CharacterTextSplitter
from langchain_groq import ChatGroq
from langchain_community.embeddings  import HuggingFaceEmbeddings
import os